name: Validate Python libraries and runs tests
description: 'Validates Python libraries and runs tests'

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.x"
    - name: Install dependencies
      shell: bash
      run: |
        python -m venv venv
        source ./venv/bin/activate
        pip install --upgrade pip
        pip install -r src/python_vor/requirements.txt
    - name: Run bearings validation
      shell: bash
      run: |
        source ./venv/bin/activate
        python3 ./tests/bearings_validation.py
